### ISSUE TITLE
issue with local-stub (homebrew) documentation

### ISSUE THREAD

**Issue by tijmenvandenbrink** [NLnetLabs/unbound-manual#45]
**Describe the bug**
The documentation [here](https://unbound.docs.nlnetlabs.nl/en/latest/use-cases/local-stub.html#homebrew) mentions the following:

```
Homebrew[¶](https://unbound.docs.nlnetlabs.nl/en/latest/use-cases/local-stub.html#homebrew)
If you installed Unbound using Homebrew, the XML file required by launchctl is already supplied during installation. The file can be found at /Library/LaunchDaemons/homebrew.mxcl.unbound.plist. To load this file we invoke the following command.

sudo launchctl load /Library/LaunchDaemons/homebrew.mxcl.unbound.plist

Now every time you restart your machine, Unbound should restart too.
```
However this file doesn't exist. In my case it was here:

`/opt/homebrew/Cellar/unbound/1.20.0/homebrew.mxcl.unbound.plist`

I copied it over to /Library/LaunchDaemons and then performed the command as per the docs. That succeeded.

**Comment by gthess** [comment]
Thanks for letting us know!
Did you install Unbound explicitly or was it already part of the system as a dependency?

**Comment by gthess** [comment]
From reading a bit online it seems that nowadays after installation you only need to do `sudo brew services start unbound` and everything will be handled automatically. Can you verify by:
1. uninstalling unbound
2. removing the /Library/LaunchDaemons/homebrew.mxcl.unbound.plist file
3. installing unbound again
4. running `sudo brew services start unbound`
5. checking that /Library/LaunchDaemons/homebrew.mxcl.unbound.plist exists.

**Comment by tijmenvandenbrink** [comment]
Worked like a charm! Thanks for the quick reply!

**Comment by gthess** [comment]
Thanks for verifying, updated that part of the documentation.
